### ISSUE TITLE
Issues for Visualization in Rviz

### ISSUE THREAD

**Issue by kc944201** [RoboticaUtnFrba/create_autonomy#212]
Hi

I want to launch create2 model in Rviz

when I type: 
roslaunch ca_description create_description.launch robot_id:=2 laser:=kinect visualize:=true
and then rosrun rviz rviz

I got the following messages about robot model

![image](https://user-images.githubusercontent.com/57080316/85089218-a2e18480-b214-11ea-80e2-dbf2eb8908f1.png)

I have no idea to solve this problem
I tried many different methods, but no effort

**Comment by eborghi10** [comment]
Hi,

I can't see the error that you're having in RViz but you can have several errors:

1. The idea of the robot is intended to work along with a real robot or a simulation in Gazebo, so you don't need to use `joint_state_publisher`. Do you have plans to use it with Gazebo?
2. Have you checked the Fixed Frame in RViz?

You can execute RViz with a predefined configuration file with this: 

```bash
roslaunch ca_tools rviz.launch
```

**Comment by kc944201** [comment]
Hi, 

I did't used joint_state_publisher, I only roslaunch ca_description create_description
and then rosrun rviz rivz, add robotmodel to display 

also I checked fixed frame is create1_tf/base_link
I think this problem that was create1_tf not link to base_link
maybe xarco file can explain


I want to launch a real robot and simulate robot in Gazebo and Rviz
but I still a beginner, I will try to understand your project

**Comment by eborghi10** [comment]
`create1_tf` is a [Tf prefix](http://wiki.ros.org/tf/Theory).

Why don't you try to run this?

```
GUI=false RVIZ=true roslaunch ca_gazebo create_empty_world.launch
```

Are you using the Dockerfile?

**Comment by kc944201** [comment]
I run GUI=false RVIZ=true roslaunch ca_gazebo create_empty_world.launch

It works now!

I don't use Dockerfile, I use Virtual Box

Thanks you very much
I need learn more knowledge about ROS
