### ISSUE TITLE
Raspberry Pi OS specification

### ISSUE THREAD

**Issue by zhuang42** [RoboticaUtnFrba/create_autonomy#222]
Sorry for another question. Please let me know if you know a better place for questions other than github issues XD.

I am trying to using raspi to control the create 2 robot, but I am confused by what OS should I run on the pi. I tried the ubuntu server which supports ROS but it lacks supports for the camera, raspbian but it doesn't support ROS. My question is should I run ROS on pi or I should have another Linux server?

Thanks for you help in advance!

**Comment by eborghi10** [comment]
I'm using an Nvidia Jetson Nano with Ubuntu Mate.
You could also use the same OS in RPi but it's no so powerful.

**Comment by zhuang42** [comment]
It means the ros master should run directly on the RPi or Jetson Nano right?

**Comment by eborghi10** [comment]
Yes, I wasn't able to get good results running `move_base` for example inside RPi and latency is considerable so I switched to a more powerful device that can run everything inside.

**Comment by zhuang42** [comment]
Thanks! I encountered some problems when installing MATE on my RPi. Just to double check, you are running 32 bits ubuntu MATE right?

**Comment by eborghi10** [comment]
Are you using the [official MATE distro](https://ubuntu-mate.org/ports/raspberry-pi/)?

**Comment by zhuang42** [comment]
Yes, I think my SD card is probably dead so I am gonna try this tomorrow.

There are armhf (32bit) and arm64 (64bit) on the official MATE distro for RPi.

By the way, how did you manage to install MATE on Jetson Nano, I don't see there is an official distro.

**Comment by eborghi10** [comment]
I just followed the [official guide](https://developer.nvidia.com/embedded/learn/get-started-jetson-nano-devkit).

**Comment by zhuang42** [comment]
Oh thanks. Maybe I should get a new hardware if I can't resolve my Pi issues ;)

**Comment by GaganBhat** [comment]
@zhuang42 I am running Ubuntu 18.04 Server on raspberry pi and I'm able to interface with the create2 over ssh from my laptop.

**Comment by zhuang42** [comment]
> @zhuang42 I am running Ubuntu 18.04 Server on raspberry pi and I'm able to interface with the create2 over ssh from my laptop.

Thank you for your reply! I managed to use the Ubuntu server 18.04 and it works well. If you wanna interact with rpi camera on ubuntu server you need to install [userland](https://github.com/raspberrypi/userland), just FYI.
