### ISSUE TITLE
Use Intel RealSense D435i

### ISSUE THREAD

**Issue by kc944201** [RoboticaUtnFrba/create_autonomy#223]
Hi

If I want add the D435i camera to the stacks, could it works?

I don't know  where to start the task, could you give me some instructions

Thanks you!

**Comment by eborghi10** [comment]
First, you have to [add the Xacro with the description of the camera](https://github.com/RoboticaUtnFrba/create_autonomy/tree/kinetic-devel/ca_description/urdf/sensors/lasers) and assign it a particular name like `d435i`.

Then, if you have to specify its pose w.r.t. the robot in [this YAML file](https://github.com/RoboticaUtnFrba/create_autonomy/blob/kinetic-devel/ca_description/urdf/sensors/lasers/poses.yaml). The name of the Xacro must match with the tag name here!

You will also need to [update these calibration values](https://github.com/RoboticaUtnFrba/create_autonomy/blob/kinetic-devel/ca_description/urdf/sensors/lasers/calibration.yaml), if you have them.

If you want to use it with a real robot, you have to [add an entry here](https://github.com/RoboticaUtnFrba/create_autonomy/blob/kinetic-devel/ca_bringup/launch/minimal.launch#L27-L32) so you can execute its driver when you choose `LASER=d435i`. Check that all the launch files are defined in the `ca_camera` package, [here](https://github.com/RoboticaUtnFrba/create_autonomy/tree/kinetic-devel/sensors/ca_camera/launch).

**Comment by kc944201** [comment]
I had been added Xacro to the path, if I want to show the model

use RVIZ=true GUI=true roslaunch ca_gazeob create_empty_world.launch laser:=d435i

the robot still show the default.

How to fix this?

Thanks you!

**Comment by eborghi10** [comment]
Use an environment variable for `laser` too, like this:

```bash
LASER=d435i RVIZ=true GUI=true roslaunch ca_gazebo create_empty_world.launch
```

Also, consider creating a PR to contribute to the community if you make some progress :smiley:

**Comment by kc944201** [comment]
Thanks you!

I already have had done simulation on Gazebo and Rviz

but when I want to use with a real robot, the ca_driver have some problem, as the following picture
![image](https://user-images.githubusercontent.com/57080316/86143045-8273cd00-bb26-11ea-8c86-e6a6f63309d9.png)

I use the newest master version in Github.

**Comment by eborghi10** [comment]
You are not working inside Docker, right?

If not, you have to set the [USB permissions](https://github.com/RoboticaUtnFrba/create_autonomy/blob/kinetic-devel/docs/INSTALLATION.md#usb-permissions).

**Comment by kc944201** [comment]
Yes, I don't use Docker.

so I need to set the permissions for USB, like this:

**sudo usermod -a -G dialout john**

Am I right?  if my user name was john

**Comment by eborghi10** [comment]
Yes, do this in your computer:

```bash
echo $USER
```

**Comment by kc944201** [comment]
Hi I type the following command

sudo usermod -a -G dialout john

but it still show the same error, what else could I do?

**Comment by kc944201** [comment]
Hi, I revise the default file of ca_driver to ttyUSB0

and now it works, but still some error when I use a real robot

sometimes it can works, but sometimes it showed the following error

[create::Serial] failed to receive data from Create. Check if robot is powered!
[create::Create] retrying to establish serial connection...
[create::Serial] serial error - Operation canceled

I ensure the cable link and the robot power was on

**Comment by yuanzhedong** [comment]
@kc944201 did you make the D435i working? Could you make a pr for that if possible, I'm also trying to use D435i, thank you.

**Comment by eborghi10** [comment]
It would be great since I also bought a D435i and I have plans to use it soon. If the PR was not created next week, I'll do it.

**Comment by kc944201** [comment]
I'm sorry, my capability is not good.

I just done combined iRobot Create2、D435i and YDLIDAR for SLAM using simulation 
In real robot, I still had some problems need to solve. like robot pose ekf

**Comment by eborghi10** [comment]
PR is almost there ^
